### ISSUE TITLE
[Bug]: generate-template --required is known to pick up required elements in optional groups and reports them as being required but it does not do it consistently

### ISSUE THREAD

**Issue by mkuehbach** [FAIRmat-NFDI/pynxtools#297] opened 2024-03-27 08:21 UTC
### What happened?

Using https://github.com/FAIRmat-NFDI/pynxtools/tree/apm-em-plugins-nxdefs-tracking 6ba8
And running ```dataconverter generate-template --nxdl NXem --required``` we find 

...
"/ENTRY[entry]/measurement/em_lab/IBEAM_COLUMN[ibeam_column]/ion_source": null,
"/ENTRY[entry]/measurement/em_lab/IBEAM_COLUMN[ibeam_column]/ion_source/probe": null,
...
which is one of these cases were a required inside an optional group is found but
the indeed really required ebeam_column with the required electron_source is not showing up
Line 344 and following group:
https://github.com/FAIRmat-NFDI/nexus_definitions/blob/c880e390ddd62ef92a09dcb307681d357e6bb913/contributed_definitions/nyaml/NXem.yaml

**Comment by lukaspie** [comment] 2024-07-03 14:46
Closed as duplicate of #266

**Closed by lukaspie** 2024-07-03 14:46 UTC
Labels: bug
